using YtDlpGui.Abstractions.Localization;

namespace YtDlpGui.Infrastructure.Localization;

public static partial class StringCatalog
{
    public static IReadOnlyDictionary<string, string> Russian { get; } = new Dictionary<string, string>
    {
        [LocKeys.ToolsChecking] = "Проверка yt-dlp и FFmpeg…",
        [LocKeys.ToolsRecheck] = "Проверить снова",
        [LocKeys.ToolsUpdate] = "Обновить компоненты",
        [LocKeys.ToolsUpdating] = "Проверка и обновление компонентов…",
        [LocKeys.ToolsUpToDate] = "Компоненты актуальны.",
        [LocKeys.ToolsUpdatedFormat] = "yt-dlp обновлен до {0}.",
        [LocKeys.ToolsUpdateFailedFormat] = "Не удалось обновить компоненты: {0}",
        [LocKeys.ToolsNotFound] = "yt-dlp не найден в системе.",
        [LocKeys.ToolsUpdatePermissionDenied] = "Отказано в доступе при обновлении yt-dlp. Запустите от имени администратора или обновите через WinGet.",
        [LocKeys.ToolsUpdateNetworkError] = "Ошибка сети при проверке обновлений. Проверьте подключение к интернету.",
        [LocKeys.ToolsUpdateCancelled] = "Обновление компонентов отменено.",
        [LocKeys.ToolsReadyFormat] = "yt-dlp {0} · {1}",
        [LocKeys.ToolsMissingFormat] = "Не найдены: {0}. Установите их (например, \"winget install yt-dlp.yt-dlp Gyan.FFmpeg\") или положите .exe файлы рядом со Scachalka.exe.",
        [LocKeys.ToolsMissingJoin] = " и ",
        [LocKeys.ToolsCheckFailed] = "Не удалось проверить инструменты — смотрите журнал.",

        [LocKeys.UrlHint] = "Ссылки на видео / аудио — одна или несколько через пробел или с новой строки. Работает Drag & drop.",
        [LocKeys.BtnAddToQueue] = "Добавить в очередь",
        [LocKeys.BtnAddTooltip] = "Ctrl+Enter",
        [LocKeys.BtnPasteAdd] = "Вставить и добавить",
        [LocKeys.BtnPasteTooltip] = "Ctrl+Shift+V — добавить ссылки сразу из буфера обмена",

        [LocKeys.LabelFormat] = "Формат",
        [LocKeys.LabelQuality] = "Качество",
        [LocKeys.LabelOutputFolder] = "Папка сохранения",
        [LocKeys.LabelLanguage] = "Язык",
        [LocKeys.BtnBrowse] = "Обзор…",
        [LocKeys.BtnOpenFolder] = "Открыть папку",
        [LocKeys.CheckDarkTheme] = "Тёмная тема",
        [LocKeys.CheckAutoUpdateOnStartup] = "Автообновление компонентов при запуске",

        [LocKeys.AdvHeader] = "Дополнительные параметры yt-dlp",
        [LocKeys.AdvPlaylists] = "Скачивать плейлисты",
        [LocKeys.AdvPlaylistsTip] = "Если ссылка на плейлист — скачивать все элементы в отдельную папку плейлиста",
        [LocKeys.AdvMetadata] = "Встраивать метаданные и главы",
        [LocKeys.AdvThumbnail] = "Встраивать обложку",
        [LocKeys.AdvThumbnailTip] = "Обложка для видео и аудио файлов (не поддерживается для WAV)",
        [LocKeys.AdvSubtitles] = "Встраивать субтитры",
        [LocKeys.AdvSubtitlesTip] = "Только для видеоформатов",
        [LocKeys.AdvSubLangsTip] = "Языки субтитров для --sub-langs, например ru,en или all (пусто = по умолчанию yt-dlp)",
        [LocKeys.AdvCookies] = "Cookies из браузера",
        [LocKeys.AdvCookiesTip] = "Использовать cookies вашего браузера для приватных, возрастных видео и видео для спонсоров",
        [LocKeys.AdvExtraArgs] = "Произвольные аргументы yt-dlp (добавляются в конец команды)",
        [LocKeys.AdvExtraArgsTip] = "Полная мощь yt-dlp: например, --limit-rate 2M --live-from-start --proxy socks5://127.0.0.1:1080",
        [LocKeys.CookieNone] = "None",

        [LocKeys.QueueTitle] = "Очередь загрузок",
        [LocKeys.QueueClearFinished] = "Очистить завершённые",
        [LocKeys.JobCancel] = "Отмена",
        [LocKeys.JobRetry] = "Повторить",
        [LocKeys.JobShowInFolder] = "Показать в папке",
        [LocKeys.JobEtaPrefix] = "Осталось",
        [LocKeys.LogHeader] = "Журнал",

        [LocKeys.StageQueued] = "В очереди",
        [LocKeys.StageQueuedRetryFormat] = "В очереди (попытка #{0})",
        [LocKeys.StageResolving] = "Получение данных…",
        [LocKeys.StageDownloading] = "Скачивание",
        [LocKeys.StageMerging] = "Объединение",
        [LocKeys.StageConverting] = "Конвертация",
        [LocKeys.StageCompleted] = "Готово",
        [LocKeys.StageFailed] = "Ошибка",
        [LocKeys.StageCanceled] = "Отменено",

        [LocKeys.StatusReady] = "Готово к работе.",
        [LocKeys.StatusNoValidUrls] = "Не найдено корректных ссылок — ожидаются http(s) адреса.",
        [LocKeys.StatusToolsMissing] = "Запуск невозможен: yt-dlp/FFmpeg отсутствуют. Установите их и нажмите «Проверить снова».",
        [LocKeys.StatusClipboardNoText] = "В буфере обмена нет текста.",
        [LocKeys.StatusCannotRetry] = "Эту загрузку нельзя повторить (некорректная ссылка).",
        [LocKeys.StatusSummaryFormat] = "Активно: {0} · В очереди: {1} · Завершено: {2} · Ошибок: {3} · Отменено: {4}",

        [LocKeys.NoteCanceled] = "Отменено пользователем.",
        [LocKeys.NoteCanceledBeforeStart] = "Отменено до запуска.",
        [LocKeys.NoteAlreadyExisted] = "Файл уже существует — скачивание пропущено.",
        [LocKeys.NoteCookiesFallback] = "Cookies браузера были заблокированы (браузер открыт) — скачано без cookies.",

        [LocKeys.BtnImportLibrary] = "Импорт Apple Music",
        [LocKeys.BtnImportLibraryTooltip] = "Выберите экспортированный файл songs.txt — каждая песня найдётся и скачается автоматически",
        [LocKeys.ImportCancel] = "Отменить импорт",
        [LocKeys.ImportFileDialogTitle] = "Выберите экспортированную библиотеку Apple Music (songs.txt)",
        [LocKeys.ImportReading] = "Чтение библиотеки…",
        [LocKeys.ImportFoundFormat] = "Найдено песен: {0}.",
        [LocKeys.ImportNoSongs] = "В файле не найдено ни одной песни.",
        [LocKeys.ImportSearchingFormat] = "Поиск {0} / {1}: {2}",
        [LocKeys.ImportMatchedFormat] = "Совпадение: {0} · Уверенность: {1}%",
        [LocKeys.ImportSkippedFormat] = "Пропущено: {0}",
        [LocKeys.ImportDownloadingFormat] = "Загрузка {0} / {1}",
        [LocKeys.ImportWaitingDownloads] = "Поиск завершён — ждём окончания загрузок…",
        [LocKeys.ImportDoneFormat] = "Библиотека импортирована. Песен: {0} · Скачано: {1} · Пропущено: {2} · С ошибкой: {3} · Время: {4}",
        [LocKeys.ImportFailedSavedFormat] = "Список неудачных сохранён: {0}",
        [LocKeys.ImportCanceled] = "Импорт отменён.",
        [LocKeys.ImportFailed] = "Импорт не удался — смотрите журнал.",
        [LocKeys.ImportAlreadyRunning] = "Импорт библиотеки уже выполняется.",
        [LocKeys.ImportReasonNoMatch] = "Совпадение не найдено",
        [LocKeys.ImportReasonLowConfidenceFormat] = "Слишком низкая уверенность ({0}%)",
        [LocKeys.ImportReasonDownloadFailed] = "Ошибка загрузки",

        [LocKeys.BtnBulkImport] = "Массовый импорт ссылок",
        [LocKeys.BtnBulkImportTooltip] = "Импортируйте CSV / TXT / JSON с сотнями ссылок — все корректные сразу попадут в очередь",
        [LocKeys.BulkFileDialogTitle] = "Выберите файл со ссылками (CSV, TXT или JSON)",
        [LocKeys.BulkReading] = "Чтение файла…",
        [LocKeys.BulkValidatingFormat] = "Найдено строк: {0} — проверка ссылок…",
        [LocKeys.BulkQueueingFormat] = "Добавление в очередь… {0} / {1}",
        [LocKeys.BulkStatsFormat] = "Корректных: {0} · Дубликатов пропущено: {1} · Некорректных: {2}",
        [LocKeys.BulkDoneFormat] = "Массовый импорт завершён. Импортировано: {0} · В очереди: {1} · Дубликатов: {2} · Некорректных: {3} · Скачано: {4} · Время: {5}",
        [LocKeys.BulkNoLinks] = "В файле не найдено ссылок.",
        [LocKeys.BulkReasonInvalid] = "Некорректная ссылка",
        [LocKeys.BulkReasonUnsupportedDomain] = "Неподдерживаемый домен",
        [LocKeys.BulkReasonMissing] = "Ссылка отсутствует",
        [LocKeys.BulkReasonDuplicate] = "Дубликат",

        [LocKeys.MatchOfficialMusicTrack] = "Официальный трек YouTube Music",
        [LocKeys.MatchOfficialAudio] = "Официальное аудио",
        [LocKeys.MatchOfficialMusicVideo] = "Официальный клип",
        [LocKeys.MatchVevo] = "Загрузка VEVO",
        [LocKeys.MatchVerifiedChannel] = "Подтверждённый канал",
        [LocKeys.MatchHighConfidence] = "Лучшее совпадение",

        [LocKeys.ErrorToolMissing] = "Нужный инструмент не найден. Установите yt-dlp и FFmpeg, затем нажмите «Проверить снова».",
        [LocKeys.ErrorInvalidUrl] = "Эта ссылка не поддерживается или не является корректной медиа-ссылкой.",
        [LocKeys.ErrorNetwork] = "Проблема сети при загрузке. Проверьте подключение и нажмите «Повторить».",
        [LocKeys.ErrorDiskFull] = "Недостаточно свободного места в папке сохранения.",
        [LocKeys.ErrorPermission] = "Нет прав на запись в папку сохранения. Выберите другую папку.",
        [LocKeys.ErrorFileExists] = "Файл уже существует в папке сохранения.",
        [LocKeys.ErrorInterrupted] = "Загрузка была прервана до завершения.",
        [LocKeys.ErrorCookieLocked] = "Не удалось прочитать cookies браузера: браузер открыт и блокирует базу cookies. Полностью закройте браузер (проверьте трей) или выберите «None» в поле «Cookies из браузера».",
        [LocKeys.ErrorUnknown] = "Загрузка неожиданно завершилась ошибкой. Подробности в журнале."
    };
}
